const { MONGODB_USER, MONGODB_PASSWORD, MONGO_DB_HOST, MONGODB_LOCAL_PORT, MONGODB_DATABASE } = process.env;

module.exports = {
  url: `mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGO_DB_HOST}:${MONGODB_LOCAL_PORT}/${MONGODB_DATABASE}?authSource=admin`,
  MONGODB_USER,
  MONGODB_PASSWORD,
  MONGO_DB_HOST,
  MONGODB_LOCAL_PORT,
  MONGODB_DATABASE,
};
