version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

  backend:
    depends_on:
      - mongodb
    build: ./backend
    restart: unless-stopped
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_PORT
    ports:
      - 8080:$BACKEND_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/backend
      - /backend/node_modules
      - ./db/backup:/backend/db/backup

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file: .env
    stdin_open: true
    tty: true
    ports:
      - 80:$FRONTEND_PORT

volumes:
  db:
