version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

  backend:
    depends_on:
      - mongodb
    build: ./backend
    restart: unless-stopped
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_PORT
      - SECRET_AES_KEY=$SECRET_AES_KEY
    ports:
      - $BACKEND_PORT:8080
    volumes:
      - ./backend:/backend
      - /backend/node_modules
      - ./db/backup:/backend/db/backup

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Dockerfile.dev for development, Dockerfile for production
    restart: unless-stopped
    environment:
      - VITE_API_URL=$API_URL
      - VITE_SECRET_AES_KEY=$SECRET_AES_KEY
    ports:
      - $FRONTEND_PORT:80
      - $FRONTEND_DEV_PORT:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - backend
    depends_on:
      - backend

volumes:
  db:

networks:
  backend:
    driver: bridge
